# Generated by Django 4.1.3 on 2022-11-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0026_alter_bookinstance_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0002_alter_reviews_book_alter_reviews_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="book.book"
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
