# Generated by Django 4.1.3 on 2022-11-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0031_alter_bookinstance_status"),
        ("reviews", "0004_alter_reviews_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="book.book"
            ),
        ),
    ]
