# Generated by Django 4.1.3 on 2022-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_author_id_alter_bookinstance_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={},
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(max_length=200),
        ),
    ]
