# Generated by Django 4.1.2 on 2022-11-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_cover_remove_book_genre_book_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
