# Generated by Django 4.1.3 on 2022-11-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_delete_booksuser_alter_bookinstance_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("w", "want to read"),
                    ("r", "read"),
                    ("cr", "currently reading"),
                ],
                default="w",
                help_text="Book status",
                max_length=2,
            ),
        ),
    ]
