# Generated by Django 4.1.3 on 2022-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_bookinstance_options_alter_bookinstance_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
