# Generated by Django 4.1.2 on 2022-11-09 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0004_bookinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cr", "currently reading"),
                    ("r", "read"),
                    ("w", "want to read"),
                ],
                default="w",
                help_text="Book status",
                max_length=2,
            ),
        ),
    ]
