# Generated by Django 4.1.2 on 2022-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_bookinstance_user_alter_bookinstance_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "permissions": (
                    ("can mark as read", "read"),
                    ("can mark as want to read", "want to read"),
                    ("can mark as currently reading", "currently reading"),
                )
            },
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "read"),
                    ("cr", "currently reading"),
                    ("w", "want to read"),
                ],
                default="w",
                help_text="Book status",
                max_length=2,
            ),
        ),
    ]
