# Generated by Django 4.1.3 on 2022-11-13 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0007_alter_bookinstance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookinstance",
            unique_together={("book", "user")},
        ),
    ]
