# Generated by Django 4.1.3 on 2022-11-13 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0010_alter_bookinstance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "read"),
                    ("w", "want to read"),
                    ("cr", "currently reading"),
                ],
                default="w",
                help_text="Book status",
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookinstance",
            unique_together={("book", "user")},
        ),
    ]
