# Generated by Django 4.1.3 on 2022-11-13 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0017_remove_bookinstance_date_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="date_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
