# Generated by Django 4.1.3 on 2022-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0019_alter_bookinstance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book/bookcovers"),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("w", "want to read"),
                    ("r", "read"),
                    ("cr", "currently reading"),
                ],
                default="w",
                help_text="Book status",
                max_length=2,
            ),
        ),
    ]
